### ISSUE TITLE
Regarding user creation

### ISSUE THREAD

**Issue by edpugantir** [eduNEXT/eox-core#167]
I have taken the Edx Devstack code from the master branch. 
I followed the instructions to deploy the Devstack. Once I deployed the devstack, I installed the Edunext eox plugin. 
I created an application for oauth and assigned edx user to the same.
Using the oauth token generated, I was able to create a new user using the api

curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxx" -d "{\"username\": \"johndoer7\",\"email\": \"johndoe7@example.com\",\"fullname\": \"John Doe\",\"password\": \"p@ssword\", \"country\":\"IN\"}"  http://<host url>:18000/eox-core/api/v1/user/

Later when I use the auth token to get the user
curl -GET  -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxx" http://<host url>:18000/eox-core/api/v1/user/?username=johndoe7

it gives the following error
No user found by johndoe7 on site example.com.

I added a couple of print debug statements in the function 'get_edxapp_user' in the file eox_core/edxapp_wrapper/backends/users_l_v1.py, 

The debug statements added are 
        print("printing users")
        print([x for x in User.objects.all()[0].__dict__.items() if not x[0].startswith('_')])

It prints only one user named ecommerce_worker. Is there something wrong in what I am doing. I would appreciate any help.

Thanks

**Comment by mariajgrimaldi** [comment]
Thanks for reaching out. I'll be looking into this.

I'll keep you posted

**Comment by mariajgrimaldi** [comment]
I tested this myself on a clean env using localhost and found that the site `localhost:18000` -in my case, in yours could be another site- didn't exist, after creating it -http://localhost:18000/admin/sites/site/add/- I could create users as usual. So please, let me know if this helps you

**Comment by MaferMazu** [comment]
@mariajgrimaldi 's solution works, if any other similar problem appears again we can open another issue.
