### ISSUE TITLE
Expose an environment parameter for the Sentry integration

### ISSUE THREAD

**Issue by blarghmatey** [eduNEXT/eox-core#173]
I realize that it's possible to set an environment variable of `SENTRY_ENVIRONMENT` to set the sentry environment designation, but it's non-trivial to expose a new environment variable to the edX runtime. It would be great to accept an `EOX_CORE_SENTRY_ENVIRONMENT` parameter from the edX `ENV_TOKENS` so that we can segment events based on which stage of a deployment they occurred.

**Comment by mariajgrimaldi** [comment]
Thanks for reaching out! I'll refer this to the team that manages our sentry integration to get their feedback.

**Comment by mariajgrimaldi** [comment]
FYI @jfavellar90 @NeOneSoft @felipemontoya

**Comment by mariajgrimaldi** [comment]
This was already implemented and merged: https://github.com/eduNEXT/eox-core/pull/174
