### ISSUE TITLE
["FEAT"] endpoint to get list of enrollment of a course

### ISSUE THREAD

**Issue by Ian2012** [eduNEXT/eox-core#225]
**Describe the solution you'd like**
Create a new endpoint called /enrollments that receives the course-id and returns the list of enrollment on the course

**Comment by MaferMazu** [comment]
We will take this feat to execute after Feb 14. Thanks @Ian2012

**Comment by MaferMazu** [comment]
This issue will be passed for product review @santiagosuarezedunext

**Comment by santiagosuarezedunext** [comment]
@Ian2012 quw más parcer 
¿Para qué necesita la info que le daría esa api?

**Comment by Ian2012** [comment]
Para que los programadores que realicen integraciones con eox-core tengan más facilidad de construir dashboards o panel de administración, además de poder generar reportes

**Comment by santiagosuarezedunext** [comment]
@Ian2012 pero lo necesitas para un proyecto en concreto?

**Comment by Ian2012** [comment]
@santiagosuarezedunext No, es un nice-to-have

**Comment by santiagosuarezedunext** [comment]
Al ser un nice to have lo voy a volver a dejar en el backlog y le daremos prioridad cuando tengamos una aplicación para esa api, que sepamos que se va usar para algun dashboard o algo.

CC: @Ian2012

**Comment by Alec4r** [comment]
@santiagosuarezedunext can we close it? and if we need it in the future, we could reopen it

**Comment by Asespinel** [comment]
@santiagosuarezedunext do we have any plans for this feature on the future sprints?

**Comment by santiagosuarezedunext** [comment]
@Asespinel not soon

**Comment by bra-i-am** [comment]
hi @Ian2012, I hope you're well

I'm just reviewing this issue and found that maybe this feature was already added to the edx-platform; here is [the endpoint](https://github.com/eduNEXT/edunext-platform/blob/176422e11b77015a6308f4a0986b43e67571aeb9/openedx/core/djangoapps/enrollments/views.py#L885) I guess could solve your requirement.

Please let us know if the endpoint is enough for you or if you think it is necessary to consider this issue so it can be solved later.
