### ISSUE TITLE
["BUG"] CHANGELOG is not updating

### ISSUE THREAD

**Issue by JuanDavidBuitrago** [eduNEXT/eox-core#236]
**Describe the bug**
When someone merged a PR the workflow make a new PR with the changes in CHANGELOG file instead to make a commit with this. The problem is that the person who merge the first PR forget merge the other one and the CHANGELOG gets outdated.

**To Reproduce**
Check the CHANGELOG file and the lasted bumpversion commits, it is no the same information.

**Expected behavior**
Once merged PR, the CHANGELOG should be updated without make other action.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Henrrypg** [comment]
Thank you for report @JuanDavidBuitrago, i will work in update the bumpversion workflow.
