### ISSUE TITLE
["BUG"] UnboundLocalError for enrollment backend

### ISSUE THREAD

**Issue by felipemontoya** [eduNEXT/eox-core#240]
**Describe the bug**
There is a bug that happens during an "except" call.

The exact line is:
https://github.com/eduNEXT/eox-core/blob/master/eox_core/edxapp_wrapper/backends/enrollment_l_v1.py#L211
```
UnboundLocalError
local variable 'err_msg' referenced before assignment
```
**To Reproduce**

We are seeing this at the sentry logs for the saas service.

**Expected behavior**
It just logs the error.

**Screenshots**

**Additional context**
https://sentry.io/organizations/edunext/issues/3373011324/?project=5181932&referrer=project-issue-stream&statsPeriod=1h

**Comment by Henrrypg** [comment]
Thank you @felipemontoya, i just opened a PR solving this issue in https://github.com/eduNEXT/eox-core/pull/242
