### ISSUE TITLE
["BUG"] TPA middleware issue

### ISSUE THREAD

**Issue by Ian2012** [eduNEXT/eox-core#243]
**Describe the bug**
eox_core.middleware.TPAExceptionMiddleware cannot be used with nuez.

```python
Traceback (most recent call last):
  File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 183, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 339, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "/openedx/venv/lib/python3.8/site-packages/eox_core/middleware.py", line 261, in process_exception
    if referer_url != reverse('signin_user') and request.view_name not in ['auth', 'complete']:
  File "/openedx/venv/src/django-wiki/wiki/models/__init__.py", line 87, in reverse
    url = original_django_reverse(*args, **kwargs)
  File "/openedx/venv/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/openedx/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'signin_user' not found. 'signin_user' is not a valid view function or pattern name.
```

The requested view `signin_user` is on the platform, but for some reason cannot be found

**Comment by JuanDavidBuitrago** [comment]
Hi @Ian2012, are you still having a problem with this? How can I replicate this behavior?

**Comment by Ian2012** [comment]
Add TPAExceptionMiddleware into the middleware, to the middleware list:

https://github.com/eduNEXT/manifests-gloria/blob/00b12e966e18df49cf3d4256fa1b135eb634bba4/environments/gloriana/plugins/settings.yml#L156 

And restart the LMS

**Comment by JuanDavidBuitrago** [comment]
I got a 404 response when I entered the link, maybe I don't have permissions on that repo.

**Comment by Ian2012** [comment]
In the LMS settings add the following (the important part is TPAExceptionMiddleware):

   ```python
 MIDDLEWARE += [
      'eox_core.middleware.PathRedirectionMiddleware',
      'eox_core.middleware.RedirectionsMiddleware',
      'eox_core.middleware.TPAExceptionMiddleware',
      'eox_tenant.middleware.AvailableScreenMiddleware',
      'eox_tenant.middleware.MicrositeCrossBrandingFilterMiddleware',
    ]
```

**Comment by JuanDavidBuitrago** [comment]
Hi @Ian2012, 

I have not been able to replicate the error, I tried misconfiguring the Provider Configuration, but only got this:

![Screenshot from 2023-02-26 22-13-02](https://user-images.githubusercontent.com/93566377/221470356-1ab95ab2-efee-40ce-9fff-deb5f61e4c16.png)
![Screenshot from 2023-02-26 22-15-50](https://user-images.githubusercontent.com/93566377/221470499-56c310b3-36ce-4598-9183-4bff7740bdfa.png)

I tried just leaving the Client Secret misconfigured, but I get a different error:

![image](https://user-images.githubusercontent.com/93566377/221471069-7798be1f-42ab-4ca2-b804-377cabf4c95f.png)

I've tried doing a few other configurations to try to replicate the problem, but none with the results you're presenting.

Please, can you give me more information, so I can replicate the error. With the information you show me, it is not possible for me to move forward. How and what configurations should I have to make it fail? At what point does the registration or login fail? What should appear in the web browser? Any other suggestions that might help in replicating the bug?

**Comment by Ian2012** [comment]
@DonatoBD @DeimerM Did you remember how to trigger this error?

**Comment by JuanDavidBuitrago** [comment]
It needs more details and context to be able to be solved, we need valid information
