### ISSUE TITLE
["FEAT"] allow to add custom params to sentry

### ISSUE THREAD

**Issue by Ian2012** [eduNEXT/eox-core#247]
I need to enable profiling with the sentry integration, but it makes sense if there would be a way to pass custom params to the sentry integration.

The profiling integration is enabled using:

```python
sentry_sdk.init(
  # ... SDK config
  _experiments={
    "profiles_sample_rate": 1.0,
  }
)
```

**Describe the solution you'd like**
There es a dictionary that is passed as **kwargs to the sentry integration:

https://github.com/eduNEXT/eox-core/blob/master/eox_core/settings/production.py#L144

**Describe alternatives you've considered**
If I'm wrong and there would be a better option or alternative to integrate please let me know.

**Comment by JuanDavidBuitrago** [comment]
Hi @Ian2012, thanks for your participation

This issue will be passed for product review @santiagosuarezedunext

**Comment by santiagosuarezedunext** [comment]
On it 👍

**Comment by santiagosuarezedunext** [comment]
@Ian2012 me comentas que necesitas profiles para saber que consume más recursos en la plataforma ¿tienen alguna iniciativa o proyecto en el que esta data hace parte?

**Comment by santiagosuarezedunext** [comment]
@Ian2012 porfa dejame acá la explicación que me contabas sobre como podrian ser los parametros cusotm.
Creo que si esto hace parte de su día a día deberías ejecutarlo, lo voy a mover a inpregress y se le podrá hacer siguimiento en nuestros sprints en [este link de Jira](https://edunext.atlassian.net/browse/DS-438?atlOrigin=eyJpIjoiYTQ1MDc0ZjM3NTVkNDg5NmE2NDRlYTc2N2FiZjU5MzMiLCJwIjoiaiJ9)

**Comment by Ian2012** [comment]
We can use a setting like that is passed as a `**kwargs` to the sentry integration:

```python
SENTRY_EXTRA_PARAMS = {
    "_experiments": { "profiles_sample_rate": 1.0, },
    ...
}
```
